# Generated by Django 5.2.14 on 2026-05-12 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0003_exercise_studio_brand_color_studio_slug_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "segment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("warmup", "Warmup"),
                            ("exercise", "Exercise"),
                            ("rest", "Rest"),
                            ("cooldown", "Cooldown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("script", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="studio.class",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio.exercise",
                    ),
                ),
            ],
            options={
                "db_table": "class_segments",
            },
        ),
    ]
