# Generated by Django 5.2.14 on 2026-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0004_classsegment"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsegment",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
