# Generated by Django 5.2.14 on 2026-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0005_classsegment_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsegment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="classsegment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name="classsegment",
            table="studio_class_segments",
        ),
    ]
