# Generated by Django 5.2.14 on 2026-05-12 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0006_classsegment_created_at_classsegment_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("audio_url", models.URLField(blank=True, null=True)),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("voice_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio",
                        to="studio.classsegment",
                    ),
                ),
            ],
            options={
                "db_table": "studio_audio_segments",
            },
        ),
    ]
