# Generated by Django 5.2.14 on 2026-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0007_audiosegment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiosegment",
            name="voice_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
