# Generated by Django 5.2.14 on 2026-05-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0010_audiosegment_studio_audiosegment_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="user",
        ),
    ]
