# Generated by Django 5.2.14 on 2026-05-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0011_remove_class_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="studio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_studio",
                to="studio.studio",
            ),
        ),
    ]
