# Generated by Django 5.2.14 on 2026-05-13 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0012_exercise_studio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studio",
            name="user",
        ),
        migrations.AddField(
            model_name="class",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
