# Generated by Django 5.2.14 on 2026-05-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0013_remove_studio_user_class_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="user",
        ),
    ]
