# Generated by Django 5.2.14 on 2026-05-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("studio_admin", "Studio Admin"),
                    ("trainer", "Trainer"),
                    ("viewer", "Viewer"),
                ],
                db_index=True,
                default="studio_admin",
                max_length=20,
            ),
        ),
    ]
