# Generated by Django 5.2.14 on 2026-05-13 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_created_by"),
        ("studio", "0013_remove_studio_user_class_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="studio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="studio.studio",
            ),
        ),
    ]
